# Generated by Django 3.0.1 on 2020-02-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivitiConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "root_url",
                    models.URLField(
                        default="https://activiti.example.com/activiti-app/api",
                        help_text="Root URL where the Activiti API is deployed.",
                        verbose_name="activiti root",
                    ),
                ),
                (
                    "auth_header",
                    models.TextField(
                        blank=True,
                        help_text="HTTP Authorization header value, required if the API is not open.",
                        verbose_name="authorization header",
                    ),
                ),
                (
                    "enterprise",
                    models.BooleanField(
                        default=True,
                        help_text="Boolean indicating if the enterprise edition of Activiti is used. The enterprise edition has different API endpoints, which needs to be taken into account to start process instances or fetch the start form configuration.",
                        verbose_name="is enterprise",
                    ),
                ),
            ],
            options={"verbose_name": "Activiti configuration",},
        ),
    ]
