# Generated by Django 2.2.10 on 2020-03-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_activiti", "0002_activiticonfig_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="activiticonfig",
            name="enabled",
            field=models.BooleanField(default=False, verbose_name="enabled"),
        ),
    ]
